language: php

php:
    - 7.0.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - ls

after_success:
- bash <(curl -s https://codecov.io/bash)
